In [1]:
import numpy as np

In [5]:
array_2x2 = np.array([[1, 2], [3, 4]])
print(array_2x2)

[[1 2]
 [3 4]]


In [2]:
array_random_3x4 = np.random.rand(3, 4)
print(array_random_3x4)

[[0.2961505  0.89715192 0.49569179 0.12177004]
 [0.6468399  0.98558578 0.78287089 0.31789255]
 [0.92583146 0.95124119 0.21224169 0.86773346]]


In [9]:
array_ones = np.ones((2, 4))
array_zeros = np.zeros((2, 4))
print(array_ones)
print(array_zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
array_random_6x3 = np.random.rand(6, 3)
print("Random 6x3 array:")
print(array_random_6x3)
array_random_6x3_transposed = array_random_6x3.T
print("\nTransposed random 6x3 array:")
print(array_random_6x3_transposed)

Random 6x3 array:
[[0.35178273 0.19015724 0.69457732]
 [0.2899586  0.56467477 0.73607012]
 [0.26071736 0.56123238 0.53691911]
 [0.19345878 0.2921118  0.43224172]
 [0.29305999 0.04598887 0.0520205 ]
 [0.63960205 0.67610803 0.29540038]]

Transposed random 6x3 array:
[[0.35178273 0.2899586  0.26071736 0.19345878 0.29305999 0.63960205]
 [0.19015724 0.56467477 0.56123238 0.2921118  0.04598887 0.67610803]
 [0.69457732 0.73607012 0.53691911 0.43224172 0.0520205  0.29540038]]


In [12]:
n = 2
p = 4
m = 8

array_nxp = np.random.rand(n, p)
array_pxm = np.random.rand(p, m)
array_dot_product = np.dot(array_nxp, array_pxm)

print("Array n x p")
print(array_nxp)
print("\nArray p x m")
print(array_pxm)
print("\nDot Product")
print(array_dot_product)

Array n x p
[[0.9722009  0.39156461 0.88251231 0.26092722]
 [0.67939759 0.35175511 0.92594794 0.85002443]]

Array p x m
[[0.04110499 0.83921608 0.99151617 0.91046408 0.70459228 0.643099
  0.9023405  0.20861467]
 [0.56768167 0.2702217  0.97607862 0.05578628 0.42726229 0.12291113
  0.38977249 0.99477557]
 [0.69263481 0.54057298 0.85577193 0.19283887 0.70704357 0.7665792
  0.30428738 0.49158267]
 [0.30554562 0.58289094 0.66591736 0.11430169 0.87363592 0.36787719
  0.29063572 0.92332522]]

Dot Product
[[0.95323028 1.55085031 2.27513599 1.10700503 1.70423608 1.44585382
  1.37424948 1.26708272]
 [1.12867658 1.66122722 2.37542062 0.91390819 2.0262874  1.50267155
  1.27895415 1.73167865]]


In [15]:
!git config --global user.email "25071095@siswa.um.edu.my"
!git config --global user.name "AliJiawi"

In [20]:
!git clone https://github.com/AliJiawi/data-science-toolkit.git

Cloning into 'data-science-toolkit'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13 (delta 3), reused 10 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (13/13), 4.09 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (3/3), done.


In [47]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [85]:
!git push https://AliJiawi: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@github.com/AliJiawi/data-science-toolkit.git main

Everything up-to-date


In [79]:
!git branch

  library/numpy
* main


In [84]:
!git commit -m "Added Tutorial3.ipynb file to repo"

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean


In [83]:
!git add .

README.md  Setup.ipynb
